### ISSUE TITLE
Different CPU usage reported in logs compared to pves stats

### ISSUE THREAD

**Issue by Traxmaxx** [fabriziosalmi/proxmox-lxc-autoscale#6]
**Describe the bug**
When looking at ` /var/log/lxc_autoscale.log` the reported CPU usage per container is

```logtalk
2024-09-29 16:25:58 - INFO - Container 104: CPU usage: 81.04%, Memory usage: 0.18MB (100.0% free of 112261MB total), Initial cores: 2, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 108: CPU usage: 71.38%, Memory usage: 0.84MB (100.0% free of 112261MB total), Initial cores: 3, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 102: CPU usage: 66.21%, Memory usage: 2.03MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 103: CPU usage: 65.19%, Memory usage: 0.56MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 101: CPU usage: 66.2%, Memory usage: 0.69MB (100.0% free of 112261MB total), Initial cores: 4, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 110: CPU usage: 81.39%, Memory usage: 0.12MB (100.0% free of 112261MB total), Initial cores: 2, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 109: CPU usage: 71.27%, Memory usage: 0.07MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
2024-09-29 16:25:58 - INFO - Container 105: CPU usage: 76.6%, Memory usage: 0.4MB (100.0% free of 112517MB total), Initial cores: 3, Initial memory: 112517MB
```

The reported usage data is very different from the stats reported via `pvesh get /cluster/resources`
```
┌─────────┬─────────┬────────┬────────────┬────────┬────────────┬────────────┬────────────┬──────────┬────────────┬──────┐
│ id      │ type    │    cpu │       disk │ maxcpu │    maxdisk │     maxmem │        mem │status    │     uptime │ vmid │
╞═════════╪═════════╪════════╪════════════╪════════╪════════════╪════════════╪════════════╪══════════╪════════════╪══════╡
│ lxc/101 │ lxc     │  0.60% │   1.33 GiB │      4 │   5.00 GiB │ 109.13 GiB │ 776.14 MiB │running   │    29m 41s │  101 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/102 │ lxc     │  1.63% │  12.23 GiB │      6 │ 130.00 GiB │ 109.13 GiB │   2.14 GiB │running   │  1h 48m 4s │  102 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/103 │ lxc     │  0.17% │   7.17 GiB │      6 │ 128.00 GiB │ 109.13 GiB │ 532.22 MiB │running   │    30m 53s │  103 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/104 │ lxc     │  0.09% │   1.06 GiB │      2 │  33.00 GiB │ 109.13 GiB │ 202.17 MiB │running   │    30m 40s │  104 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/105 │ lxc     │  1.55% │   4.22 GiB │      3 │ 512.00 GiB │ 109.38 GiB │ 455.40 MiB │running   │    28m 26s │  105 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/108 │ lxc     │  0.51% │   3.18 GiB │      3 │ 128.00 GiB │ 109.13 GiB │ 917.75 MiB │running   │     30m 5s │  108 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/109 │ lxc     │  0.03% │  51.59 GiB │      6 │ 256.00 GiB │ 109.13 GiB │  83.05 MiB │running   │ 1h 49m 28s │  109 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/110 │ lxc     │  0.16% │   1.24 GiB │      2 │ 512.00 GiB │ 109.13 GiB │ 115.88 MiB │running   │     30m 1s │  110 │
├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
│ lxc/112 │ lxc     │  0.00% │ 772.97 MiB │      1 │  19.52 GiB │ 512.00 MiB │     0.00 B │running   │ 12w 6d 18h │  112 │
└─────────┴─────────┴────────┴────────────┴────────┴────────────┴────────────┴────────────┴──────────┴────────────┴──────
```

**To Reproduce**
Install scripts from current `main` and also run `lxc_autoscale_autoconf.sh`

Compare output of `tail -f /var/log/lxc_autoscale.log` with the output of `pvesh get /cluster/resources`

**Expected behavior**
I expected the CPU usage to somewhat match between both reported metrics.

**Server (please complete the following information):**
 - OS: Linux 6.8.8-3-pve (2024-07-16T16:16Z)
- Manager: pve-manager/8.2.7/3e0176e6bb2ade3b

**Comment by fabriziosalmi** [comment]
This if correct will need investigation. I tested it many times with no such differences!

**Comment by rtfmjoey** [comment]
Same here:

`2024-09-30 21:05:51 - INFO - Starting resource allocation process...
2024-09-30 21:05:51 - INFO - Ignoring LXC Containers: {'126'}
2024-09-30 21:05:51 - INFO - Initial resources before adjustments: 14 cores, 112315 MB memory
2024-09-30 21:05:51 - INFO - Current resource usage for all containers:
2024-09-30 21:05:51 - INFO - Container 125: CPU usage: 65.97%, Memory usage: 34.51MB (93.26% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 120: CPU usage: 51.41%, Memory usage: 20.14MB (96.07% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 122: CPU usage: 66.13%, Memory usage: 28.25MB (99.59% free of 6912MB total), Initial cores: 2, Initial memory: 6912MB
2024-09-30 21:05:51 - INFO - Container 121: CPU usage: 51.81%, Memory usage: 8.94MB (98.25% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 124: CPU usage: 53.71%, Memory usage: 19.45MB (98.48% free of 1278MB total), Initial cores: 4, Initial memory: 1278MB
2024-09-30 21:05:51 - INFO - Container 123: CPU usage: 52.62%, Memory usage: 10.12MB (99.34% free of 1536MB total), Initial cores: 2, Initial memory: 1536MB
2024-09-30 21:05:51 - INFO - Container 128: CPU usage: 76.17%, Memory usage: 21.84MB (95.73% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 127: CPU usage: 79.4%, Memory usage: 72.45MB (92.97% free of 1030MB total), Initial cores: 5, Initial memory: 1030MB
2024-09-30 21:05:51 - INFO - Container 130: CPU usage: 46.19%, Memory usage: 23.72MB (96.91% free of 768MB total), Initial cores: 2, Initial memory: 768MB
2024-09-30 21:05:51 - INFO - Container 129: CPU usage: 54.3%, Memory usage: 10.87MB (99.29% free of 1536MB total), Initial cores: 2, Initial memory: 1536MB
2024-09-30 21:05:51 - INFO - Container 131: CPU usage: 56.41%, Memory usage: 55.97MB (94.43% free of 1004MB total), Initial cores: 3, Initial memory: 1004MB
2024-09-30 21:05:51 - INFO - Container 134: CPU usage: 57.94%, Memory usage: 7.43MB (98.55% free of 512MB total), Initial cores: 4, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 132: CPU usage: 60.18%, Memory usage: 56.22MB (89.02% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 133: CPU usage: 62.92%, Memory usage: 20.92MB (99.86% free of 15104MB total), Initial cores: 5, Initial memory: 15104MB
2024-09-30 21:05:51 - INFO - Container 135: CPU usage: 70.52%, Memory usage: 8.02MB (98.43% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 136: CPU usage: 79.13%, Memory usage: 77.96MB (84.77% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 137: CPU usage: 41.79%, Memory usage: 53.77MB (94.38% free of 957MB total), Initial cores: 3, Initial memory: 957MB
2024-09-30 21:05:51 - INFO - Container 138: CPU usage: 49.25%, Memory usage: 40.73MB (92.04% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 139: CPU usage: 32.5%, Memory usage: 14.73MB (97.12% free of 512MB total), Initial cores: 1, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 142: CPU usage: 48.91%, Memory usage: 18.31MB (96.42% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 140: CPU usage: 49.79%, Memory usage: 27.69MB (94.59% free of 512MB total), Initial cores: 1, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Final resources after adjustments: 14 cores, 112315 MB memory
`

vs

┌──────────────────────────┬─────────┬─────────────┬───────────────────┬────────┬────────────┬─────────┬───────┬────────┬────────────┬─────────────┬────────────┬─────────────────────────┬──
│ id                       │ type    │ cgroup-mode │ content           │    cpu │       disk │ hastate │ level │ maxcpu │    maxdisk │      maxmem │        mem │ name                    │ n
╞══════════════════════════╪═════════╪═════════════╪═══════════════════╪════════╪════════════╪═════════╪═══════╪════════╪════════════╪═════════════╪════════════╪═════════════════════════╪══
│ lxc/100                  │ lxc     │             │                   │  0.00% │     0.00 B │         │       │      1 │  15.00 GiB │    2.00 GiB │     0.00 B │ cv-pkg                  │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/101                  │ lxc     │             │                   │  0.00% │     0.00 B │         │       │      1 │  15.00 GiB │    2.00 GiB │     0.00 B │ kerio-test              │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/120                  │ lxc     │             │                   │  0.17% │   6.63 GiB │         │       │      2 │  15.00 GiB │  512.00 MiB │  58.39 MiB │ Pi-Hole                 │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/121                  │ lxc     │             │                   │  0.02% │   1.06 GiB │         │       │      3 │  15.00 GiB │  512.00 MiB │  45.03 MiB │ NUT                     │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/122                  │ lxc     │             │                   │  0.79% │  17.32 GiB │         │       │      2 │  50.00 GiB │    6.75 GiB │   1.90 GiB │ Database                │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/123                  │ lxc     │             │                   │  1.37% │   5.49 GiB │         │       │      2 │  15.00 GiB │    1.50 GiB │ 150.42 MiB │ TVHeadend               │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/124                  │ lxc     │             │                   │  0.08% │   6.03 GiB │         │       │      4 │  15.00 GiB │    1.25 GiB │  99.12 MiB │ LibreNMS01              │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/125                  │ lxc     │             │                   │  3.57% │   3.19 GiB │         │       │      2 │  15.00 GiB │  512.00 MiB │ 171.10 MiB │ Domoticz                │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/126                  │ lxc     │             │                   │  0.31% │   4.94 GiB │         │       │      4 │  15.00 GiB │    6.00 GiB │ 459.98 MiB │ Download                │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/127                  │ lxc     │             │                   │  0.17% │   1.94 GiB │         │       │      5 │  15.00 GiB │    1.01 GiB │ 745.06 MiB │ Unifi                   │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/128                  │ lxc     │             │                   │  0.05% │   1.63 GiB │         │       │      6 │  15.00 GiB │  512.00 MiB │ 106.70 MiB │ NNTPProxy               │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/129                  │ lxc     │             │                   │  1.02% │   1.80 GiB │         │       │      2 │  15.00 GiB │    1.50 GiB │ 152.14 MiB │ NAS                     │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/130                  │ lxc     │             │                   │  0.62% │   1.92 GiB │         │       │      2 │  15.00 GiB │  768.00 MiB │ 181.87 MiB │ LMS                     │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/131                  │ lxc     │             │                   │  0.13% │   4.48 GiB │         │       │      3 │  15.00 GiB │ 1004.00 MiB │ 378.80 MiB │ TeslaMate               │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/132                  │ lxc     │             │                   │  0.63% │   4.62 GiB │         │       │      3 │  15.00 GiB │  512.00 MiB │ 281.81 MiB │ ReverseProxy            │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/133                  │ lxc     │             │                   │ 34.62% │   6.50 GiB │         │       │      5 │  15.00 GiB │   14.75 GiB │   2.94 GiB │ ZoneMinder              │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/134                  │ lxc     │             │                   │  0.02% │   1.01 GiB │         │       │      4 │  15.00 GiB │  512.00 MiB │  37.70 MiB │ mDNS                    │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/135                  │ lxc     │             │                   │  0.02% │   1.02 GiB │         │       │      6 │  15.00 GiB │  512.00 MiB │  40.71 MiB │ MQTT                    │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/136                  │ lxc     │             │                   │  0.54% │   6.23 GiB │         │       │      6 │  15.00 GiB │  512.00 MiB │ 398.36 MiB │ Influx                  │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/137                  │ lxc     │             │                   │  0.57% │   3.12 GiB │         │       │      3 │  15.00 GiB │  957.00 MiB │ 481.53 MiB │ DSMR                    │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/138                  │ lxc     │             │                   │  0.90% │   3.81 GiB │         │       │      3 │  15.00 GiB │  512.00 MiB │ 202.41 MiB │ Z2M                     │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/139                  │ lxc     │             │                   │  0.36% │   6.73 GiB │         │       │      1 │  15.00 GiB │  512.00 MiB │  75.11 MiB │ EVCC                    │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/140                  │ lxc     │             │                   │  1.22% │   5.24 GiB │         │       │      1 │  15.00 GiB │  512.00 MiB │ 141.21 MiB │ Kodi-Headless           │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/142                  │ lxc     │             │                   │  0.08% │   2.13 GiB │         │       │      2 │  15.00 GiB │  512.00 MiB │  88.70 MiB │ Commvault-DS            │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ lxc/200                  │ lxc     │             │                   │  0.00% │     0.00 B │         │       │      1 │  15.00 GiB │    1.00 GiB │     0.00 B │ template-ubuntu-lxc     │ p
├──────────────────────────┼─────────┼─────────────┼───────────────────┼────────┼────────────┼─────────┼───────┼────────┼────────────┼─────────────┼────────────┼─────────────────────────┼──
│ node/pve01               │ node    │           2 │                   │ 23.46% │ 159.43 GiB │         │       │     16 │   6.17 TiB │  125.68 GiB │  84.53 GiB │                         │ p
└──────────────────────────┴─────────┴─────────────┴───────────────────┴────────┴────────────┴─────────┴───────┴────────┴────────────┴─────────────┴────────────┴─────────────────────────┴──

Version: pve-manager/8.2.6/414ce79a1d42d6bc (running kernel: 6.8.12-2-pve)

**Comment by rtfmjoey** [comment]
Same here:

```
2024-09-30 21:05:51 - INFO - Starting resource allocation process...
2024-09-30 21:05:51 - INFO - Ignoring LXC Containers: {'126'}
2024-09-30 21:05:51 - INFO - Initial resources before adjustments: 14 cores, 112315 MB memory
2024-09-30 21:05:51 - INFO - Current resource usage for all containers:
2024-09-30 21:05:51 - INFO - Container 125: CPU usage: 65.97%, Memory usage: 34.51MB (93.26% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 120: CPU usage: 51.41%, Memory usage: 20.14MB (96.07% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 122: CPU usage: 66.13%, Memory usage: 28.25MB (99.59% free of 6912MB total), Initial cores: 2, Initial memory: 6912MB
2024-09-30 21:05:51 - INFO - Container 121: CPU usage: 51.81%, Memory usage: 8.94MB (98.25% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 124: CPU usage: 53.71%, Memory usage: 19.45MB (98.48% free of 1278MB total), Initial cores: 4, Initial memory: 1278MB
2024-09-30 21:05:51 - INFO - Container 123: CPU usage: 52.62%, Memory usage: 10.12MB (99.34% free of 1536MB total), Initial cores: 2, Initial memory: 1536MB
2024-09-30 21:05:51 - INFO - Container 128: CPU usage: 76.17%, Memory usage: 21.84MB (95.73% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 127: CPU usage: 79.4%, Memory usage: 72.45MB (92.97% free of 1030MB total), Initial cores: 5, Initial memory: 1030MB
2024-09-30 21:05:51 - INFO - Container 130: CPU usage: 46.19%, Memory usage: 23.72MB (96.91% free of 768MB total), Initial cores: 2, Initial memory: 768MB
2024-09-30 21:05:51 - INFO - Container 129: CPU usage: 54.3%, Memory usage: 10.87MB (99.29% free of 1536MB total), Initial cores: 2, Initial memory: 1536MB
2024-09-30 21:05:51 - INFO - Container 131: CPU usage: 56.41%, Memory usage: 55.97MB (94.43% free of 1004MB total), Initial cores: 3, Initial memory: 1004MB
2024-09-30 21:05:51 - INFO - Container 134: CPU usage: 57.94%, Memory usage: 7.43MB (98.55% free of 512MB total), Initial cores: 4, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 132: CPU usage: 60.18%, Memory usage: 56.22MB (89.02% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 133: CPU usage: 62.92%, Memory usage: 20.92MB (99.86% free of 15104MB total), Initial cores: 5, Initial memory: 15104MB
2024-09-30 21:05:51 - INFO - Container 135: CPU usage: 70.52%, Memory usage: 8.02MB (98.43% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 136: CPU usage: 79.13%, Memory usage: 77.96MB (84.77% free of 512MB total), Initial cores: 6, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 137: CPU usage: 41.79%, Memory usage: 53.77MB (94.38% free of 957MB total), Initial cores: 3, Initial memory: 957MB
2024-09-30 21:05:51 - INFO - Container 138: CPU usage: 49.25%, Memory usage: 40.73MB (92.04% free of 512MB total), Initial cores: 3, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 139: CPU usage: 32.5%, Memory usage: 14.73MB (97.12% free of 512MB total), Initial cores: 1, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 142: CPU usage: 48.91%, Memory usage: 18.31MB (96.42% free of 512MB total), Initial cores: 2, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Container 140: CPU usage: 49.79%, Memory usage: 27.69MB (94.59% free of 512MB total), Initial cores: 1, Initial memory: 512MB
2024-09-30 21:05:51 - INFO - Final resources after adjustments: 14 cores, 112315 MB memory
```

vs

┌──────────────────────────┬─────────┬────────┬─
│ id                       │ type    │    cpu │ 
╞══════════════════════════╪═════════╪════════╪═
│ lxc/100                  │ lxc     │  0.00% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/101                  │ lxc     │  0.00% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/120                  │ lxc     │  0.17% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/121                  │ lxc     │  0.02% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/122                  │ lxc     │  0.79% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/123                  │ lxc     │  1.37% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/124                  │ lxc     │  0.08% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/125                  │ lxc     │  3.57% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/126                  │ lxc     │  0.31% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/127                  │ lxc     │  0.17% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/128                  │ lxc     │  0.05% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/129                  │ lxc     │  1.02% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/130                  │ lxc     │  0.62% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/131                  │ lxc     │  0.13% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/132                  │ lxc     │  0.63% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/133                  │ lxc     │ 34.62% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/134                  │ lxc     │  0.02% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/135                  │ lxc     │  0.02% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/136                  │ lxc     │  0.54% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/137                  │ lxc     │  0.57% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/138                  │ lxc     │  0.90% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/139                  │ lxc     │  0.36% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/140                  │ lxc     │  1.22% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/142                  │ lxc     │  0.08% │ 
├──────────────────────────┼─────────┼────────┼─
│ lxc/200                  │ lxc     │  0.00% │ 
├──────────────────────────┼─────────┼────────┼─
│ node/pve01               │ node    │ 23.46% │ 
└──────────────────────────┴─────────┴────────┴─

Version: pve-manager/8.2.6/414ce79a1d42d6bc (running kernel: 6.8.12-2-pve)

**Comment by fabriziosalmi** [comment]
> **Describe the bug** When looking at ` /var/log/lxc_autoscale.log` the reported CPU usage per container is
> 
> ```logtalk
> 2024-09-29 16:25:58 - INFO - Container 104: CPU usage: 81.04%, Memory usage: 0.18MB (100.0% free of 112261MB total), Initial cores: 2, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 108: CPU usage: 71.38%, Memory usage: 0.84MB (100.0% free of 112261MB total), Initial cores: 3, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 102: CPU usage: 66.21%, Memory usage: 2.03MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 103: CPU usage: 65.19%, Memory usage: 0.56MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 101: CPU usage: 66.2%, Memory usage: 0.69MB (100.0% free of 112261MB total), Initial cores: 4, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 110: CPU usage: 81.39%, Memory usage: 0.12MB (100.0% free of 112261MB total), Initial cores: 2, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 109: CPU usage: 71.27%, Memory usage: 0.07MB (100.0% free of 112261MB total), Initial cores: 6, Initial memory: 112261MB
> 2024-09-29 16:25:58 - INFO - Container 105: CPU usage: 76.6%, Memory usage: 0.4MB (100.0% free of 112517MB total), Initial cores: 3, Initial memory: 112517MB
> ```
> 
> The reported usage data is very different from the stats reported via `pvesh get /cluster/resources`
> 
> ```
> ┌─────────┬─────────┬────────┬────────────┬────────┬────────────┬────────────┬────────────┬──────────┬────────────┬──────┐
> │ id      │ type    │    cpu │       disk │ maxcpu │    maxdisk │     maxmem │        mem │status    │     uptime │ vmid │
> ╞═════════╪═════════╪════════╪════════════╪════════╪════════════╪════════════╪════════════╪══════════╪════════════╪══════╡
> │ lxc/101 │ lxc     │  0.60% │   1.33 GiB │      4 │   5.00 GiB │ 109.13 GiB │ 776.14 MiB │running   │    29m 41s │  101 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/102 │ lxc     │  1.63% │  12.23 GiB │      6 │ 130.00 GiB │ 109.13 GiB │   2.14 GiB │running   │  1h 48m 4s │  102 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/103 │ lxc     │  0.17% │   7.17 GiB │      6 │ 128.00 GiB │ 109.13 GiB │ 532.22 MiB │running   │    30m 53s │  103 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/104 │ lxc     │  0.09% │   1.06 GiB │      2 │  33.00 GiB │ 109.13 GiB │ 202.17 MiB │running   │    30m 40s │  104 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/105 │ lxc     │  1.55% │   4.22 GiB │      3 │ 512.00 GiB │ 109.38 GiB │ 455.40 MiB │running   │    28m 26s │  105 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/108 │ lxc     │  0.51% │   3.18 GiB │      3 │ 128.00 GiB │ 109.13 GiB │ 917.75 MiB │running   │     30m 5s │  108 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/109 │ lxc     │  0.03% │  51.59 GiB │      6 │ 256.00 GiB │ 109.13 GiB │  83.05 MiB │running   │ 1h 49m 28s │  109 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/110 │ lxc     │  0.16% │   1.24 GiB │      2 │ 512.00 GiB │ 109.13 GiB │ 115.88 MiB │running   │     30m 1s │  110 │
> ├─────────┼─────────┼────────┼────────────┼────────┼────────────┼────────────┼────────────┼──────────┼────────────┼──────┤
> │ lxc/112 │ lxc     │  0.00% │ 772.97 MiB │      1 │  19.52 GiB │ 512.00 MiB │     0.00 B │running   │ 12w 6d 18h │  112 │
> └─────────┴─────────┴────────┴────────────┴────────┴────────────┴────────────┴────────────┴──────────┴────────────┴──────
> ```
> 
> **To Reproduce** Install scripts from current `main` and also run `lxc_autoscale_autoconf.sh`
> 
> Compare output of `tail -f /var/log/lxc_autoscale.log` with the output of `pvesh get /cluster/resources`
> 
> **Expected behavior** I expected the CPU usage to somewhat match between both reported metrics.
> 
> **Server (please complete the following information):**
> 
> * OS: Linux 6.8.8-3-pve (2024-07-16T16:16Z)
> * Manager: pve-manager/8.2.7/3e0176e6bb2ade3b

Is your PVE 8.2.6 too as the other reported here?

**Comment by rtfmjoey** [comment]
Looks like the issue is with getting the CPU stats:

```
root@pve01:~# pct exec 128 -- cat /proc/stat | grep ^cpu
cpu  20240497 7838 6067649 56501872 142066 0 66324 0 14224674 0
cpu5 20240497 7838 6067649 56501872 142066 0 66324 0 14224674 0
```


vs 

```
root@pve01:~# pct exec 128 -- cat /proc/loadavg
0.08 0.02 0.01 1/118 3312494
```


Wouldn't it be a lot easier to use loadavg?

**Comment by fabriziosalmi** [comment]
should be fixed [here](https://github.com/fabriziosalmi/proxmox-lxc-autoscale/commit/b63a75d355586b6735fdd4933c8cea9aeaf92b25), can you confirm?

**Comment by fabriziosalmi** [comment]
Using now different methods with prioritised loadavg. In a close future I'll add also pvesh in cluster contexts.

```
root@dell:~# /usr/bin/python3 /usr/local/bin/lxc_autoscale/lxc_autoscale.py
2024-10-02 05:45:38 - Starting resource allocation process...
2024-10-02 05:45:45 - CPU usage for container 108 using Load Average Method: 0.0%
2024-10-02 05:45:45 - CPU usage for container 112 using Load Average Method: 0.0%
2024-10-02 05:45:45 - CPU usage for container 106 using Load Average Method: 1.33%
2024-10-02 05:45:45 - CPU usage for container 111 using Load Average Method: 0.33%
2024-10-02 05:45:45 - CPU usage for container 103 using Load Average Method: 0.0%
2024-10-02 05:45:46 - CPU usage for container 114 using Load Average Method: 0.0%
2024-10-02 05:45:47 - Starting resource allocation process...
2024-10-02 05:45:47 - Ignoring LXC Containers: set()
2024-10-02 05:45:47 - Initial resources before adjustments: 40 cores, 124757 MB memory
2024-10-02 05:45:47 - Current resource usage for all containers:
2024-10-02 05:45:47 - Container 108: CPU usage: 0.0%, Memory usage: 3.07MB (99.96% free of 7680MB total), Initial cores: 3, Initial memory: 7680MB
2024-10-02 05:45:47 - Container 111: CPU usage: 0.33%, Memory usage: 29.14MB (99.64% free of 8192MB total), Initial cores: 3, Initial memory: 8192MB
2024-10-02 05:45:47 - Container 112: CPU usage: 0.0%, Memory usage: 4.44MB (99.94% free of 7680MB total), Initial cores: 3, Initial memory: 7680MB
2024-10-02 05:45:47 - Container 106: CPU usage: 1.33%, Memory usage: 4.96MB (99.94% free of 7680MB total), Initial cores: 3, Initial memory: 7680MB
2024-10-02 05:45:47 - Container 103: CPU usage: 0.0%, Memory usage: 9.74MB (99.87% free of 7680MB total), Initial cores: 3, Initial memory: 7680MB
2024-10-02 05:45:47 - Container 114: CPU usage: 0.0%, Memory usage: 2.11MB (99.97% free of 7680MB total), Initial cores: 3, Initial memory: 7680MB
2024-10-02 05:45:47 - Container 108 - CPU usage below lower threshold.
2024-10-02 05:45:47 - Container 108 - Decrement: 1, New cores: 2
2024-10-02 05:45:48 - No notification system configured.
2024-10-02 05:45:48 - Decreasing memory for container 108 by 512MB...
2024-10-02 05:45:50 - No notification system configured.
2024-10-02 05:45:50 - Container 111 - CPU usage below lower threshold.
2024-10-02 05:45:50 - Container 111 - Decrement: 1, New cores: 2
2024-10-02 05:45:51 - No notification system configured.
2024-10-02 05:45:51 - Container 112 - CPU usage below lower threshold.
2024-10-02 05:45:51 - Container 112 - Decrement: 1, New cores: 2
2024-10-02 05:45:53 - No notification system configured.
2024-10-02 05:45:53 - Decreasing memory for container 112 by 512MB...
2024-10-02 05:45:54 - No notification system configured.
2024-10-02 05:45:54 - Container 106 - CPU usage below lower threshold.
2024-10-02 05:45:54 - Container 106 - Decrement: 1, New cores: 2
2024-10-02 05:45:56 - No notification system configured.
2024-10-02 05:45:56 - Decreasing memory for container 106 by 512MB...
2024-10-02 05:45:57 - No notification system configured.
2024-10-02 05:45:57 - Container 103 - CPU usage below lower threshold.
2024-10-02 05:45:57 - Container 103 - Decrement: 1, New cores: 2
2024-10-02 05:45:58 - No notification system configured.
2024-10-02 05:45:58 - Decreasing memory for container 103 by 512MB...
2024-10-02 05:46:00 - No notification system configured.
2024-10-02 05:46:00 - Container 114 - CPU usage below lower threshold.
2024-10-02 05:46:00 - Container 114 - Decrement: 1, New cores: 2
2024-10-02 05:46:01 - No notification system configured.
2024-10-02 05:46:01 - Decreasing memory for container 114 by 512MB...
2024-10-02 05:46:02 - No notification system configured.
2024-10-02 05:46:02 - Final resources after adjustments: 46 cores, 127317 MB memory
2024-10-02 05:46:02 - Resource allocation process completed. Next run in 600 seconds.
```

**Comment by ckkibet** [comment]
Greetings @fabriziosalmi 

this doesnt seem to be ok. I am still having the same experience as @rtfmjoey and @Traxmaxx

**Comment by fabriziosalmi** [comment]
re-opening and fixing ☕
